name=IWC
version=1.0.0
author=Bjarke Gotfredsen <bjarke@gotfredsen.com>
maintainer=Bjarke Gotfredsen <bjarke@gotfredsen.com>
sentence=This is an Arduino library for the IWC sensor
paragraph=which is based on capacative sensing.
category=Sensors
url=https://github.com/domino4com/IWC
architectures=*
depends=bblanchon/ArduinoJson
